--creating table
    CREATE TABLE members(
        member_id INT GENERATED BY DEFAULT AS IDENTITY,
        first_name VARCHAR2(100) NOT NULL,
        last_name VARCHAR2(100) NOT NULL,
        gender CHAR(1) NOT NULL,
        dob DATE NOT NULL,
        email VARCHAR2(255) NOT NULL,
        PRIMARY KEY(member_id)
    );



    SELECT 
        index_name, 
        index_type, 
        visibility, 
        status 
    FROM 
        all_indexes
    WHERE 
        table_name = 'MEMBERS';

    CREATE INDEX members_last_name_i 
    ON members(last_name);


    SELECT 
        index_name, 
        index_type, 
        visibility, 
        status 
    FROM 
        all_indexes
    WHERE 
        table_name = 'MEMBERS';
        

    SELECT * FROM members
    WHERE last_name = 'Harse';



    EXPLAIN PLAN FOR
    SELECT * FROM members
    WHERE last_name = 'Harse';

    SELECT 
        PLAN_TABLE_OUTPUT 
    FROM 
        TABLE(DBMS_XPLAN.DISPLAY());


    DROP INDEX index_name;

    DROP INDEX members_last_name_i;
--index
    CREATE INDEX members_name_i
    ON members(last_name,first_name);

    SELECT * 
    FROM members
    WHERE last_name LIKE 'A%' 
        AND first_name LIKE 'M%';
    EXPLAIN PLAN FOR
    SELECT * 
    FROM members
    WHERE last_name LIKE 'A%' 
        AND first_name LIKE 'M%';
        
        
    SELECT 
        PLAN_TABLE_OUTPUT 
    FROM 
        TABLE(DBMS_XPLAN.DISPLAY());
    
    
--drop index 
    DECLARE index_count INTEGER;
    BEGIN
    SELECT COUNT(*) INTO index_count
        FROM USER_INDEXES
        WHERE INDEX_NAME = 'index_name';

    IF index_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP INDEX index_name';
    END IF;
    END;
    /

    CREATE UNIQUE INDEX members_email_i
    ON members(email);


    INSERT INTO members(first_name, last_name, gender, dob, email)
    VALUES('Pegpa','Elce','F',DATE '1990-01-02','pelce0@trellian.com');
    --
    CREATE TABLE unq_idx_demo(
        a INT,
        b INT
    );   
--creating TWO columns 
    CREATE UNIQUE INDEX unq_idx_demo_ab_i
    ON unq_idx_demo(a,b);


    INSERT INTO unq_idx_demo(a,b)
    VALUES(1,1);

    INSERT INTO unq_idx_demo(a,b)
    VALUES(1,2);

    INSERT INTO unq_idx_demo(a,b)
    VALUES(1,1);


    EXPLAIN PLAN FOR
    SELECT * FROM members
    WHERE UPPER(last_name) = 'SANS';


    SELECT 
        PLAN_TABLE_OUTPUT 
    FROM 
        TABLE(DBMS_XPLAN.DISPLAY());
        

    CREATE BITMAP INDEX members_gender_i
    ON members(gender);
    EXPLAIN PLAN FOR 
    SELECT 
        *
    FROM
        members
    WHERE
        gender = 'F';

        
    SELECT 
        PLAN_TABLE_OUTPUT 
    FROM 
        TABLE(DBMS_XPLAN.DISPLAY());      


    SELECT column, COUNT(*)
    FROM table_name
    GROUP BY column;

    CREATE TABLE bitmap_index_demo(
        id INT GENERATED BY DEFAULT AS IDENTITY,
        active NUMBER NOT NULL,
        PRIMARY KEY(id)
    );

    CREATE BITMAP INDEX bitmap_index_demo_active_i
    ON bitmap_index_demo(active);

